apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v1
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
      version: v1.0.0
  template:
    metadata:
      labels:
        app: app
        version: v1.0.0
    spec:
      containers:
        - name: app
          image: argoproj/rollouts-demo:green
          ports:
          - name: http
            containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: app-v1
  labels:
    app: app
spec:
  selector:
    app: app
    version: v1.0.0
  ports:
  - name: http
    port: 8080
    targetPort: http